"""
Module: embedder
Purpose:
- Take the text chunks generated by pdf_processor.
- Convert them into vector embeddings using a local open-source model via sentence-transformers.
- Save these embeddings into a local ChromaDB collection for long-term storage and quick searching.
"""


def create_embeddings_and_store(chunks: list):
    pass
